name: get_time_ago
description: A Dart package to convert and format `DateTime` objects into human-readable 'time ago' strings like '20 seconds ago', 'a minute ago', or '7 hours ago'.

version: 2.0.0

homepage: https://pub.dev/packages/get_time_ago
repository: https://github.com/nixrajput/get-time-ago
issue_tracker: https://github.com/nixrajput/get-time-ago/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  intl: ">=0.18.0 <0.20.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

topics:
  - get-time-ago
  - gettimeago
  - timeago
  - time-ago

funding:
  - https://ko-fi.com/nixrajput
  - https://www.buymeacoffee.com/nixrajput
  - https://github.com/sponsors/nixrajput